# "#" this is a comment
#This is a docker-compose file to build all the apps in oxzion3.0. See readme.

#specifying version according to docker engine release version.
#refer to https://docs.docker.com/compose/compose-file/
version: "3.7"

#making sevices
services:
        #First service app
        chat:
                build:
                       #location of Dockerfile                       
                       context: ./mattermost/docker                       
                       network: "host"                       
                       #name of the dockerfile                       
                       dockerfile: Dockerfile                    
                #using ports is not compatible when network_mode="host"                    
                network_mode: "host"
                #Mount host paths or named volumes, specified as sub-options to a service.
                volumes:
                          - "./mattermost:/mattermost" 
                #adding metadata to the resulting image using Docker labels.
                labels:
                        com.oxapp.description: "Chat App"
        #php apps                           
        phpapps:
                build:
                        context: ./docker
                        dockerfile: Dockerfile
                #Expose ports, can add multiple
                network_mode: "host"
                volumes:
                          - "/var/lib/oxzion/rainloop/data:/var/www/public/rainloop/data"
                          - ".:/integrations"
                labels:
                        com.example.description: "PHP Apps"
                stdin_open: true
                tty: true
        #third app and fourth app(running camel and activemq together)
        camel:
                build:
                        context: ./camel/docker
                        dockerfile: Dockerfile

                network_mode: "host"
                volumes:
                          - "./camel:/workspace/app"
                labels:
                        com.oxapp.description: "Apache Activemq/Camel"
        #fifth app
#        elasticsearch:
#                #Specify the image to start the container from. Can either be a repository/tag or a partial image ID.
#                image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
#                container_name: elasticsearch_654
#                environment:
#                          - http.host=0.0.0.0
#                          - transport.host=0.0.0.0
#                          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#                volumes:
#                          - esdata:/usr/share/elasticsearch/data
#                          - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#                ports:
#                          - 9200:9200
#                          - 9300:9300
#                labels:
#                        com.oxapp.description: "Elastic Search"
#                #Override the default ulimits for a container. You can either specify a single limit as an integer or soft/hard limits #as a mapping.
#                ulimits:
#                          memlock:
#                                    soft: -1
#                                    hard: -1
#                          nofile:
#                                    soft: 65536
#                                    hard: 65536
#                mem_limit: 2g
#                cap_add:
#                          - IPC_LOCK
#        #part of elastic search
#        kibana:
#                image: docker.elastic.co/kibana/kibana:6.5.4
#                container_name: kibana_654
#                environment:
#                          - SERVER_HOST=0.0.0.0
#                volumes:
#                          - ./kibana.yml:/usr/share/kibana/config/kibana.yml
#                ports:
#                          - 5601:5601
#        #part of elastic search
#        headPlugin:
#                image: mobz/elasticsearch-head:5
#                container_name: head_654
#                ports:
#                          - 9100:9100

#volumes:
#  esdata:
#    driver: local        