<?php

namespace Oxzion\Model\Entity;
use Oxzion\Model\Entity;

class File extends Entity{

    protected $data = array(
        'id' => NULL,
        'assessid' => NULL,
        'name' => NULL,
        'description' => NULL,
        'htmltext' => NULL,
        'leaf' => NULL,
        'color' => NULL,
        'durationunit' => NULL,
        'percentdone' => NULL,
        'duration' => NULL,
        'orgid' => NULL,
        'formid' => NULL,
        'createdid' => NULL,
        'original_createdid' => NULL,
        'modifiedid' => NULL,
        'assignedto' => NULL,
        'assignedgroup' => NULL,
        'date_created' => NULL,
        'date_modified' => NULL,
        'ownergroupid' => NULL,
        'parentinstformid' => NULL,
        'status' => NULL,
        'duplicate' => NULL,
        'startdate' => NULL,
        'nextactiondate' => NULL,
        'emailaddress1' => NULL,
        'enddate' => NULL,
        'cost' => NULL,
        'starpoints' => NULL,
        'testerid' => NULL,
        'testercode' => NULL,
        'field3' => NULL,
        'tags' => NULL,
        'category' => NULL,
        'goals' => NULL,
        'kracategory' => NULL,
        'krasubcategory' => NULL,
        'observer' => NULL,
        'location' => NULL,
        'pod' => '0',
        'observeravatardel' => NULL,
        'observergroupdel' => NULL,
        'comment_moderator' => '1',
        'reffield1' => NULL,
        'reffield2' => NULL,
        'reffield3' => NULL,
        'reffield4' => NULL,
        'reffield5' => NULL,
        'f1' => NULL,
        'f2' => NULL,
        'f3' => NULL,
        'f4' => NULL,
        'f5' => NULL,
        'f6' => NULL,
        'f7' => NULL,
        'f8' => NULL,
        'f9' => NULL,
        'f10' => NULL,
        'f11' => NULL,
        'f12' => NULL,
        'f13' => NULL,
        'f14' => NULL,
        'f15' => NULL,
        'f16' => NULL,
        'f17' => NULL,
        'f18' => NULL,
        'f19' => NULL,
        'f20' => NULL,
        'f21' => NULL,
        'f22' => NULL,
        'f23' => NULL,
        'f24' => NULL,
        'f25' => NULL,
        'f26' => NULL,
        'f27' => NULL,
        'f28' => NULL,
        'f29' => NULL,
        'f30' => NULL,
        'fbig1' => NULL,
        'fbig2' => NULL,
        'fbig3' => NULL,
        'fbig4' => NULL,
        'fbig5' => NULL,
        'fbig6' => NULL,
        'fbig7' => NULL,
        'fbig8' => NULL,
        'fbig9' => NULL,
        'fbig10' => NULL,
        'fbig11' => NULL,
        'fbig12' => NULL,
        'fbig13' => NULL,
        'fbig14' => NULL,
        'fbig15' => NULL,
        'fbig16' => NULL,
        'fbig17' => NULL,
        'fbig18' => NULL,
        'fbig19' => NULL,
        'fbig20' => NULL,
        'locked' => '0',
        'points_flag' => '0',
    );

    public function __construct($data=null){
        $this->tablename = 'instanceforms';
        parent::__construct($data,$this);
    }
    public function checkAccess($avatar){
        $groups = array_column($avatar->getGroups(),"id");
        if(in_array($this->data['assignedgroup'], $groups)||in_array($this->data['ownergroupid'], $groups)||$this->data['assignedto']==$avatar->id||$this->data['createdid']==$avatar->id||$this->data['original_createdid']==$avatar->id){
            return $this;
        } else {
            return array('response'=>'No Access');
        }
    }
}