FROM xqdocker/ubuntu-openjdk:jdk-8 as build

ENV REQUIRED_PACKAGES="bash curl" 
RUN apt-get update && apt-get install -y $REQUIRED_PACKAGES

ENV ACTIVEMQ_VERSION 5.15.6
ENV ACTIVEMQ apache-activemq-$ACTIVEMQ_VERSION
ENV ACTIVEMQ_TCP=61616 ACTIVEMQ_AMQP=5672 ACTIVEMQ_STOMP=61613 ACTIVEMQ_MQTT=1883 ACTIVEMQ_WS=61614 ACTIVEMQ_UI=8161
ENV SHA512_VAL=a1b931a25c513f83f4f712cc126ee67a2b196ea23a243aa6cafe357ea03f721fba6cb566701e5c0e1f2f7ad8954807361364635c45d5069ec2dbf0ba5c6b588b

ENV ACTIVEMQ_HOME /opt/activemq


RUN curl "https://archive.apache.org/dist/activemq/$ACTIVEMQ_VERSION/$ACTIVEMQ-bin.tar.gz" -o $ACTIVEMQ-bin.tar.gz

# Validate checksum
RUN if [ "$SHA512_VAL" != "$(sha512sum $ACTIVEMQ-bin.tar.gz | awk '{print($1)}')" ];\
    then \
        echo "sha512 values doesn't match! exiting."  && \
        exit 1; \
    fi;

RUN tar xzf $ACTIVEMQ-bin.tar.gz -C  /opt && \
    ln -s /opt/$ACTIVEMQ $ACTIVEMQ_HOME && \
    useradd -r -M -d $ACTIVEMQ_HOME activemq && \
    chown -R activemq:activemq /opt/$ACTIVEMQ && \
    chown -h activemq:activemq $ACTIVEMQ_HOME && \
    mkdir -p /app 

ARG HOST
ARG DB_HOST
ARG DB_USERNAME
ARG DB_PASSWORD
ARG API_DB
ARG QUARTZ_DB
ARG ELASTIC_CLUSTER

ENV HOST=${HOST}
ENV DB_HOST=${DB_HOST}
ENV API_DB=${API_DB}
ENV QUARTZ_DB=${QUARTZ_DB}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV ELASTIC_CLUSTER=${ELASTIC_CLUSTER}

EXPOSE $ACTIVEMQ_TCP $ACTIVEMQ_AMQP $ACTIVEMQ_STOMP $ACTIVEMQ_MQTT $ACTIVEMQ_WS $ACTIVEMQ_UI $SERVER_PORT

WORKDIR /workspace/app

ENTRYPOINT ["./docker-entrypoint.sh"]
