version: '3.5'
services:
    zf:
        build:
            context: .
            args:
                DB_USERNAME: ${DB_USERNAME}
                DB_PASSWORD: ${DB_PASSWORD}
                DB_HOST: ${DB_HOST}
                CAMUNDA_DB: ${CAMUNDA_DB}
                API_DB : ${API_DB}
        network_mode: "host"    
        ports:
            - "8090:8090"
        