

<?php
    $script = "<script type='text/javascript' charset='utf-8'>window.location = '". $redirectUrl. "'"."</script>";
    $noscript = "<noscript><meta http-equiv='refresh' content='1;url=".$redirectUrl."'></noscript>";
    $body = "<body>If you are not redirected, please <a href='".$redirectUrl."'>click here</a> to continue.</body>";
    echo "<html><head>".$script.$noscript."</head>".$body."</html>"

?>



