parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: oro_crm
    database_user: crmuser
    database_password: Crmpasswd321!
    database_driver_options: {  }
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_port: null
    mailer_encryption: null
    mailer_user: null
    mailer_password: null
    websocket_bind_address: 0.0.0.0
    websocket_bind_port: 8076
    websocket_frontend_host: '*'
    websocket_frontend_port: 8076
    websocket_frontend_path: ''
    websocket_backend_host: '*'
    websocket_backend_port: 8076
    websocket_backend_path: ''
    websocket_backend_transport: tcp
    websocket_backend_ssl_context_options: {  }
    web_backend_prefix: ''
    session_handler: session.handler.native_file
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    installed: '2019-06-14T13:36:09+00:00'
    assets_version: ce7511ce
    assets_version_strategy: time_hash
    message_queue_transport: dbal
    message_queue_transport_config: null
