version: '3.5'
services:
    camel:
        build:
            context: ./docker
            args:
                HOST: ${HOST}
                DB_USERNAME: ${DB_USERNAME}
                DB_PASSWORD: ${DB_PASSWORD}
                DB_HOST: ${DB_HOST}
                QUARTZ_DB: ${QUARTZ_DB}
                API_DB : ${API_DB}
                ELASTIC_CLUSTER : ${ELASTIC_CLUSTER}
        network_mode: "host"    
        ports:
            - "8161:8161"
            - "8085:8085"
            - "61616:61616"
            - "5672:5672"
            - "61613:61613"
            - "1883:1883"
            - "61614:61614"
        volumes:
            - ./:/workspace/app
            - ../../:/app      